# Generated by Django 5.2.5 on 2025-08-17 13:36

import videos_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail_url', models.ImageField(upload_to='thumbnails/')),
                ('category', models.CharField(choices=[('horror', 'Horror'), ('action', 'Action'), ('drama', 'Drama'), ('animals', 'Animals'), ('documentary', 'Documentary')], max_length=50)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=videos_app.models.video_file_path)),
            ],
        ),
    ]
