# Generated by Django 5.2.5 on 2025-08-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0002_video_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
